name: travel_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc_test: ^8.3.0
  cached_network_image: ^3.1.0
  cupertino_icons: ^0.1.3
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.3
  flag: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  freezed: any
  google_fonts: ^2.1.0
  injectable: ^1.4.1
  injectable_generator: ^1.4.1
  json_serializable: any
  lint: ^1.5.3
  lottie: ^1.1.0
  mockito: ^5.0.16

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/json/data.json
